/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package bot_core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class double_array_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int num_values;
    public double values[];
 
    public double_array_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xcaec3c875dbc427bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(bot_core.double_array_t.class))
            return 0L;
 
        classes.add(bot_core.double_array_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.num_values); 
 
        for (int a = 0; a < this.num_values; a++) {
            outs.writeDouble(this.values[a]); 
        }
 
    }
 
    public double_array_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public double_array_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static bot_core.double_array_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        bot_core.double_array_t o = new bot_core.double_array_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.num_values = ins.readInt();
 
        this.values = new double[(int) num_values];
        for (int a = 0; a < this.num_values; a++) {
            this.values[a] = ins.readDouble();
        }
 
    }
 
    public bot_core.double_array_t copy()
    {
        bot_core.double_array_t outobj = new bot_core.double_array_t();
        outobj.utime = this.utime;
 
        outobj.num_values = this.num_values;
 
        outobj.values = new double[(int) num_values];
        if (this.num_values > 0)
            System.arraycopy(this.values, 0, outobj.values, 0, this.num_values); 
        return outobj;
    }
 
}

