/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package bot_core;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class gps_satellite_info_list_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int num_sats;
    public bot_core.gps_satellite_info_t sat_info[];
 
    public gps_satellite_info_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x1f4e7c464d4ad1e4L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(bot_core.gps_satellite_info_list_t.class))
            return 0L;
 
        classes.add(bot_core.gps_satellite_info_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + bot_core.gps_satellite_info_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.num_sats); 
 
        for (int a = 0; a < this.num_sats; a++) {
            this.sat_info[a]._encodeRecursive(outs); 
        }
 
    }
 
    public gps_satellite_info_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public gps_satellite_info_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static bot_core.gps_satellite_info_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        bot_core.gps_satellite_info_list_t o = new bot_core.gps_satellite_info_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.num_sats = ins.readInt();
 
        this.sat_info = new bot_core.gps_satellite_info_t[(int) num_sats];
        for (int a = 0; a < this.num_sats; a++) {
            this.sat_info[a] = bot_core.gps_satellite_info_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public bot_core.gps_satellite_info_list_t copy()
    {
        bot_core.gps_satellite_info_list_t outobj = new bot_core.gps_satellite_info_list_t();
        outobj.utime = this.utime;
 
        outobj.num_sats = this.num_sats;
 
        outobj.sat_info = new bot_core.gps_satellite_info_t[(int) num_sats];
        for (int a = 0; a < this.num_sats; a++) {
            outobj.sat_info[a] = this.sat_info[a].copy();
        }
 
        return outobj;
    }
 
}

