/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package robotlocomotion;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class header_t implements lcm.lcm.LCMEncodable
{
    public int seq;
    public long utime;
    public String frame_name;
 
    public header_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x09272c333198c72aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(robotlocomotion.header_t.class))
            return 0L;
 
        classes.add(robotlocomotion.header_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeInt(this.seq); 
 
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.frame_name.length()]; this.frame_name.getChars(0, this.frame_name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public header_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public header_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static robotlocomotion.header_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        robotlocomotion.header_t o = new robotlocomotion.header_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.seq = ins.readInt();
 
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.frame_name = new String(__strbuf);
 
    }
 
    public robotlocomotion.header_t copy()
    {
        robotlocomotion.header_t outobj = new robotlocomotion.header_t();
        outobj.seq = this.seq;
 
        outobj.utime = this.utime;
 
        outobj.frame_name = this.frame_name;
 
        return outobj;
    }
 
}

