/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package robotlocomotion;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class image_array_t implements lcm.lcm.LCMEncodable
{
    public robotlocomotion.header_t header;
    public int num_images;
    public robotlocomotion.image_t images[];
 
    public image_array_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3afa7aac7daa3b4eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(robotlocomotion.image_array_t.class))
            return 0L;
 
        classes.add(robotlocomotion.image_array_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + robotlocomotion.header_t._hashRecursive(classes)
             + robotlocomotion.image_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        this.header._encodeRecursive(outs); 
 
        outs.writeInt(this.num_images); 
 
        for (int a = 0; a < this.num_images; a++) {
            this.images[a]._encodeRecursive(outs); 
        }
 
    }
 
    public image_array_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public image_array_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static robotlocomotion.image_array_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        robotlocomotion.image_array_t o = new robotlocomotion.image_array_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.header = robotlocomotion.header_t._decodeRecursiveFactory(ins);
 
        this.num_images = ins.readInt();
 
        this.images = new robotlocomotion.image_t[(int) num_images];
        for (int a = 0; a < this.num_images; a++) {
            this.images[a] = robotlocomotion.image_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public robotlocomotion.image_array_t copy()
    {
        robotlocomotion.image_array_t outobj = new robotlocomotion.image_array_t();
        outobj.header = this.header.copy();
 
        outobj.num_images = this.num_images;
 
        outobj.images = new robotlocomotion.image_t[(int) num_images];
        for (int a = 0; a < this.num_images; a++) {
            outobj.images[a] = this.images[a].copy();
        }
 
        return outobj;
    }
 
}

