/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package robotlocomotion;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class residual_observer_state_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public short num_joints;
    public String joint_name[];
    public float residual[];
    public float gravity[];
    public float internal_torque[];
    public float foot_contact_torque[];
 
    public residual_observer_state_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x8c1b4e93b8978c7dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(robotlocomotion.residual_observer_state_t.class))
            return 0L;
 
        classes.add(robotlocomotion.residual_observer_state_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        outs.writeShort(this.num_joints); 
 
        for (int a = 0; a < this.num_joints; a++) {
            __strbuf = new char[this.joint_name[a].length()]; this.joint_name[a].getChars(0, this.joint_name[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
        for (int a = 0; a < this.num_joints; a++) {
            outs.writeFloat(this.residual[a]); 
        }
 
        for (int a = 0; a < this.num_joints; a++) {
            outs.writeFloat(this.gravity[a]); 
        }
 
        for (int a = 0; a < this.num_joints; a++) {
            outs.writeFloat(this.internal_torque[a]); 
        }
 
        for (int a = 0; a < this.num_joints; a++) {
            outs.writeFloat(this.foot_contact_torque[a]); 
        }
 
    }
 
    public residual_observer_state_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public residual_observer_state_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static robotlocomotion.residual_observer_state_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        robotlocomotion.residual_observer_state_t o = new robotlocomotion.residual_observer_state_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.num_joints = ins.readShort();
 
        this.joint_name = new String[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.joint_name[a] = new String(__strbuf);
        }
 
        this.residual = new float[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            this.residual[a] = ins.readFloat();
        }
 
        this.gravity = new float[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            this.gravity[a] = ins.readFloat();
        }
 
        this.internal_torque = new float[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            this.internal_torque[a] = ins.readFloat();
        }
 
        this.foot_contact_torque = new float[(int) num_joints];
        for (int a = 0; a < this.num_joints; a++) {
            this.foot_contact_torque[a] = ins.readFloat();
        }
 
    }
 
    public robotlocomotion.residual_observer_state_t copy()
    {
        robotlocomotion.residual_observer_state_t outobj = new robotlocomotion.residual_observer_state_t();
        outobj.utime = this.utime;
 
        outobj.num_joints = this.num_joints;
 
        outobj.joint_name = new String[(int) num_joints];
        if (this.num_joints > 0)
            System.arraycopy(this.joint_name, 0, outobj.joint_name, 0, this.num_joints); 
        outobj.residual = new float[(int) num_joints];
        if (this.num_joints > 0)
            System.arraycopy(this.residual, 0, outobj.residual, 0, this.num_joints); 
        outobj.gravity = new float[(int) num_joints];
        if (this.num_joints > 0)
            System.arraycopy(this.gravity, 0, outobj.gravity, 0, this.num_joints); 
        outobj.internal_torque = new float[(int) num_joints];
        if (this.num_joints > 0)
            System.arraycopy(this.internal_torque, 0, outobj.internal_torque, 0, this.num_joints); 
        outobj.foot_contact_torque = new float[(int) num_joints];
        if (this.num_joints > 0)
            System.arraycopy(this.foot_contact_torque, 0, outobj.foot_contact_torque, 0, this.num_joints); 
        return outobj;
    }
 
}

